"use client";

import Helmet from "react-helmet";

export default function CSSLandscape() {
  return (
    <div>
      <h1>CSS Landscape</h1>
      I've always been impressed when people are able to use CSS to create
      complex shapes and art. I also always like when CSS is combined with
      JavaScript to create interesting parallax effects. I decided it would be
      fun to combine the concepts, and have a parallax CSS landscape that was
      generated by JavaScript. This is what I ended up with:
      <div id="css-landscape-container" className="game-container"></div>
      What you see is rendered using only CSS and DOM elements, no images, no
      canvases.
      <Helmet>
        <script src="/scripts/css-landscape/css-landscape.js"></script>
      </Helmet>
    </div>
  );
}
